name: pconnect_mobile
description: Local-network phone controller for Pconnect.
publish_to: "none"

version: 0.2.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  connectivity_plus: ^6.0.5
  network_info_plus: ^6.0.2
  permission_handler: ^11.3.1
  android_intent_plus: ^5.2.0
  file_picker: ^8.0.0
  mobile_scanner: ^5.1.1
  sensors_plus: ^5.0.1
  flutter_local_notifications: ^17.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
